### ISSUE TITLE
Simplify3D Postprocessing

### ISSUE THREAD

**Issue by joeynuggetz** [DrLex0/MightyVariableFan#4] opened 2019-04-13 20:46 UTC
Just followed this guide and put everything together and all is working and all calibrations are good. Only problem is I use S3D and not Slic3r and was wondering if you could provide a way to post-process the GCODE that is output from S3D. Tried feeding some S3D gcode into the phython script and it complained that M126/M127 commands are being used. Found some in the start gcode (also some in your Slic3r start/stop snippets). Can you provide some guidance please? I really need to use S3D due to the processes.

**Comment by DrLex0** [comment] 2019-04-13 23:53
You need to use the alternate ‘MVF’ start snippet with this system. If you then configure S3D to output G-code for a RepRap printer instead of Sailfish, it might work. At the least this should get you to a point where the script breaks due to my assumptions of how Slic3r formats G-code. If that's the case then it should only be a matter of making the G-code parsing more universal.

**Comment by joeynuggetz** [comment] 2019-04-14 02:47
I think I figured out the problem. S3D appends the top of the gcode file with comments of all the slicer settings which includes the start/end gcode and perhaps the END_MARKER that the script is looking for- ";- - - Custom finish printing G-code for FlashForge Creator Pro - - -" Is it that simple?

 I removed all the comments at the start of the file and re-ran the processor and it worked. Haven't printed with it yet but the M300 commands are in there.  With the gcode as is straight from S3D the script will give a "WARNING: M126 and/or M127 command(s) were found inside the body of the G-code. Most likely, your fan will not work for this print. Are you sure your slicer is outputting G-code with M106 commands (e.g. RepRap G-code flavor)?"

For giggles I added this to S3D post processing in hopes of removing all the comments on top and this seemed to take care of the issue. 

{STRIP ";   "}

**Comment by DrLex0** [comment] 2019-04-14 11:00
Can you provide an example of a non-processed G-code file as S3D produces?
The detection of neither the M126/127 code nor the end line marker should trip on anything that is prepended with the ‘;’ comment character.

**Comment by joeynuggetz** [comment] 2019-04-14 13:17
Sure, here you go
[S3D_unprocessed.zip](https://github.com/DrLex0/MightyVariableFan/files/3077391/S3D_unprocessed.zip)

**Comment by DrLex0** [comment] 2019-04-14 14:29
It seems S3D does append S (speed) arguments to M126 commands even though this is useless for a non-modified FFCP. This means I could add an ‘s3d’ mode to the script that simply accepts M126 commands with S arguments, then you wouldn't need to do anything special except invoke the script with this option. The rest of the G-code seems compatible with the script.

I am slightly confused though if the current script works for you with this particular file if you strip the comment lines from it, because it contains M126 and M127 commands in the code itself. The script should still complain even with all comment lines removed and no M300 sequences should be inserted except maybe one at the end of the file. If everything works as intended, you should see a bunch of M300 sequences around the first layer changes with steadily increasing effective speeds, until `RAMP_UP_ZMAX` has been reached.

**Comment by joeynuggetz** [comment] 2019-04-14 14:51
Thanks for looking. I haven’t tried stripping the comments from this code but I followed the same process yesterday and stripped the comments and the script doesn’t complain when I post process. If you could have a version of the script that is S3D frilendly that would be cool and I would be happy to test. I will try and run the scripts with the comments disabled. I did it yesterday and like you said I saw m300 command right at the 2nd layer where I had the fan set to kick in. 

BTW if anyone hasn’t said so recently let me say that you are a freaking genius. Having the ability to PWM a fan on the flashforge is epic. I really enjoyed doing this little modification. You’re the man. Wish I had half your brain power. :-)

**Comment by joeynuggetz** [comment] 2019-04-14 17:30
I see you're working on some commits. :-)

**Comment by DrLex0** [comment] 2019-04-14 17:32
I have updated the script. There was indeed an issue with the ‘`@body`’ marker inside the parameter dump being wrongly detected as the start of the actual print. This is now fixed so you no longer need to strip the comments, and you also don't need to set the printer type to RepRap anymore if you invoke the script with the ‘-S’ option.

**Comment by joeynuggetz** [comment] 2019-04-14 18:08
Awesome!. Just tested with the -S option and it worked. I see the M300 commands in the output now. Nice job. 
I'm trying to adopt your startup and ending gcode snippets that I'm sure you spent a lot of time on to S3D. There's one variable that Slic3r uses **G1 Z[first_layer_height] F1500; move to first layer height** that I can't find an equivalent to in S3D. I found the variables for extruder and bed heating and I'm sorta stuck on this one.

**Comment by DrLex0** [comment] 2019-04-14 19:29
I cannot find this either and I doubt it is available at all. However, it isn't crucial to use the actual first layer height in the start code. You can hard-code any sensible value, I would recommend 0.25 since that's usually the first layer height I use and it works well for the priming extrusion.

**Comment by DrLex0** [comment] 2019-06-02 16:01
I'm going to close this assuming S3D support is now good enough, if there's anything else, just open a new issue :)

**Closed as completed by DrLex0** 2019-06-02 16:01 UTC
